# Dockerfile-backend
FROM golang:latest AS builder
WORKDIR /app

# Copy go mod and sum files
COPY ./src/backend/go.mod ./src/backend/go.sum ./
# Download all dependencies. Dependencies will be cached if the go.mod and go.sum files are not changed
RUN go mod download

# Copy the source from the current directory to the Working Directory inside the container
COPY ./src/backend/ .
# Build the Go app
RUN go build -o main .

# Command to run the executable
CMD ["./main"]
